[
/section (Part III: Process Instructions / Cheatsheet) /endsection

(*1. Volvelle Assembly*)
/linebreak
(You will need: a craft knife, scissors, card stock, brass)
(fasteners, and the volvelle printouts from Module 0.)

/startlist
/listitem1 (Cut out each disc with scissors. Then, cut out the)
  (windows on the top discs with the craft knife.) /endlistitem
/listitem1 (Cut out the small center circle in each bottom disc.)
  (Cut a slit along one of the small lines of the cross in each)
  (top disc.) /endlistitem
/listitem1 (Attach the discs with a brass fastener through the)
  (center holes.) /endlistitem

/paragraph
(*2. Create New Seed (Initial* $k$ *Shares)*)
/linebreak
(You will need: the addition volvelle, dice de-biasing worksheet,)
(checksum worksheet, pencil, eraser, and your secret seed.)
(For each of your initial $k$ shares, you should:)
/startlist
/listitem1 (Generate random data by rolling dice, following the)
  (instructions on the dice de-biasing worksheet.) /endlistitem
/listitem1 (Follow the instructions on the checksum worksheet to)
  (affix a checksum.) /endlistitem

/paragraph
(*3. Create New Seed (Additional/Derived Shares)*)
/linebreak
(You will need: the addition volvelle, fusion/translation)
(wheel, translation worksheet, and pencil.)
/startlist
/listitem1 (Translate the initial shares using the symbols in the)
  (derived shares section.) /endlistitem
/listitem1 (Add the translated initial shares to get the new)
  (derived share.) /endlistitem

/paragraph
(*4. Recover Secret*)
/linebreak
(You will need: the recovery wheel, and everything used for)
  (derived share creation (see above).)
  (To recover your secret, you must have $k$ shares available.)

/startlist
/listitem1 (Look up their recovery symbols with the recovery wheel.) /endlistitem
/listitem1 (Fuse all of the symbols for each share with the)
  (fusion wheel to get a symbol for each share.) /endlistitem
/listitem1 (Translate the share by that symbol.) /endlistitem
/listitem1 (Add all of the translated shares to get your secret.) /endlistitem

/paragraph
(*5. Verify Shares*)
/linebreak
(You will need: the addition volvelle, checksum worksheet, pencil, eraser, and the share to validate.)
/startlist
/listitem1 (Copy the share data into the bold boxes of the checksum worksheet.) /endlistitem
/listitem1 (Follow the instructions to complete the worksheet, checking that)
  (the final result is `SECRETSHARE32`.) /endlistitem

/paragraph
(*6. Correct Shares*)
/linebreak
(You will need: the addition volvelle, checksum worksheet, pencil, eraser, and the share to validate.)
/startlist
/listitem1 (Follow the instructions above to verify your share.) /endlistitem
/listitem1 (If the result is not `SECRETSHARE32`, enter the result into the online tool.)
   (This data does not contain any information about your share data, only about the errors.)
   /endlistitem
/listitem1 (Add the given values to the given characters in your share, according to the online)
   (instructions.) /endlistitem

/paragraph
(*X. Deriving Addresses and Spending Coins*)
/linebreak
(It is an open question as to how to derive addresses or spend coins using paper computers.)
(Please contact Pearlwort at `pearlwort@secretcodex32.com` if you believe you have insight)
(into this.)
] drawPageContent
