[
/startText

/paragraph
(There are three volvelles in this codex. Each serves a different)
(fuction, and has slightly different usage instructions.)

/paragraph
(*1. Addition.* To add two characters, turn the addition wheel to)
(one of them and look through the window corresponding to the)
(other. It does not matter which character is which; addition is)
(symmetric.)

/paragraph
(*2. Recovery.* When recovering a secret, you will need to look up)
("recovery symbols" that will be used. To do this with the)
(recovery wheel, turn the wheel to the share you want to)
(translate. Mark down the symbols pointed to by the $other shares$)
(indices and fuse these together.)

/paragraph
($Important$: Unlike the other wheels, the recovery wheel can)
(easily be used in the wrong order. Be careful!)

/paragraph
(*3. Translation & Fusion.* A common task in the scheme is)
(to "translate" share data by a given recovery)
(symbol. To do so,)
(turn the translation/fusion wheel so that the window on)
(the fusion side is showing the correct symbol. Then, turn)
(the wheel over; the translation side will act like a decoder)
(ring, mapping characters to characters.)

/paragraph
(Sometimes you will need to translate a share by multiple symbols)
(at once. To accomplish this, turn the fusion wheel to the)
(first symbol. Find the next symbol on the inner wheel; whatever)
(symbol that it's pointing to, turn the fusion wheel to)
(that symbol. Repeat for all of the symbols that you need to)
(combine. The fusion wheel will wind up at the final)
(product. You can now turn the wheel over to translate by this)
(symbol. As with addition, the order in which you take your)
(original symbols does not matter.)
] drawPageContent
